# Generated by Django 6.0.7 on 2026-07-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
